backend:
  name: git-gateway
  branch: main

media_folder: "assets" # Folder where user-uploaded files will go
public_folder: "/assets"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - file: "index.md"
        label: "Homepage"
        name: "home"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Body", name: "body", widget: "markdown" }
